# Development overrides for docker-compose.yml
services:
  nginx:
    ports:
      - "8080:80" # For local development access

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=/api
    ports:
      - "3000:3000" # Expose port for direct access in development
    depends_on:
      backend:
        condition: service_healthy

  backend:
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - RELOAD=True
      - CORS_ORIGINS=http://localhost:8080,http://localhost:3000
      - FRONTEND_URL=http://localhost:8080
      - COOKIE_DOMAIN=localhost
      - COOKIE_SECURE=false
      - COOKIE_SAMESITE=lax
      - CAS_SERVICE_URL=http://localhost:8080/whispr/api/verify/callback
    ports:
      - "8000:8000" # Expose port for direct access in development
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
