services:
  nginx:
    image: nginx:alpine
    container_name: whispr-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - whispr-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whispr-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost/api
    networks:
      - whispr-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whispr-backend
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/whispr
      - DATABASE_NAME=whispr
      - JWT_SECRET=change_me_in_production
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION=86400
    networks:
      - whispr-network
      - backend-db-network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: whispr-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=whispr
    networks:
      - backend-db-network

networks:
  whispr-network:
    driver: bridge
  backend-db-network:
    driver: bridge

volumes:
  postgres_data: