from app.models.user import User
from app.models.professor import Professor
from app.models.professor_social_media import ProfessorSocialMedia
from app.models.course import Course
from app.models.course_instructor import CourseInstructor
from app.models.review import Review
from app.models.reply import Reply
from app.models.vote import Vote
from app.models.notification import Notification
from app.models.used_email import UsedEmail
from app.models.user_followers import user_followers